language: ruby
rbenv:
- 2.7.2
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
env:
  global:
  - secure: 414uFgwd2yK2GlUSX0+L9GAuLOUrd1m8WyNd0z1jmYNMYTQMWR7FqWwtKfRYhPPpFYqJqxHNUDUbJYQH3lRPY3jAJ7e42PP9lIvQd8IlALkF81mNNtmyOSEgP84a2U0OTD1XAh7J6IYpDvyC8bWVb8oV61WMkU6KvLQ90V5y7Om1K7HDpnIeb3jvoBdTdyPwYVkuSyYwkJpN4fyPzsohwCqWfnfSiiGhX+WpDe1WK7KNbYiYSYSetxSYXM0Z6FDVqI+pzSphhkV0C84KkTFAyZEpZU6JmSppm+QgBGslIxijDNgxQg8ZCs1pJKLNCj++grqoQU1pBLTgDzCcnnJMVLjIDZ0ecSG3SJatH64fZFbWHFcmbLTgsvoinWvPh2XmESfQDfnvl8VaKUS80K/zDL0x6ts2OKNSG2JTLBtqtj6KiNUhu/sFRLDGYr/VoR6aYCJ8adfWWBi9VnyfUxbHszGGsiTs1TJFO0zOEmvndLTfzlB2Evj1tV3MGBGvXPFOWiKSPcET+k6ABFOlKbkkySSK6UQYakvIckwypeZBz24J1GdEe5LSngfk4fTrpSe7ct39sGKw4vDzdDjTSk5mCMwghaCAYKum9D2WaAuWjFaQVScIUqYtVp27dR9pIr7W95z/AQwJz6Hk6yrjYVBK/kZnbANFs6oksrmBZ8lBJHc=
deploy:
  provider: heroku
  api_key:
    secure: lMLHvC+aylsm6BzjD8B83ynZHX39YFwGVUrjTsr2d11mLYc6+0vhNy2Ce40VMBOjPdgGSwLfzNeeFq3QiKuyJGtzgdV+vYNLbaqnz0ABExpvra0Ui5aJbDg1fYMLFB/lQFk9SLF8dXBEu4aaNYs6VXDQEY7ox1/2RbuZFfR8ArrZYkdrtgL0ZFYdIqceFPCa+msa4CAwhM+W7gTTb8KAVUr1MHg90jWMnwCN1Z8LPSqWedrFC0SQpD2LwmGoRrDyLQNGwYMmC7dhIenXjm48sMlHlIAU9D0u05jsDkBKZQ3eYxYnjYfIkaxTGzfz71XmjB21o+p/INIdqyWNMJwFkDphjYRLrw7ev8T6y6R0KYdVfMPAJuuvcJgOudQVOPMscuh+6gOdMhQV4va/7yviJ99rOIkT6VrqnvSIJegS22LeOaHFQ59tObOasKJn54T09J+qLJdnO/lmrkzD0jV/eorYr8/RifQH57AppYK/hLIVhKmI+vybw+g/23kA1AMkiB2xY8idgJmyRjxT3Ajg9BzizpLkJzp1ydBJ3aOKJVcO8Rs8SGSfLMKQqG+Hxy4tQNmI1s3dtTPw2y2puIHsc6Hbib7CeS7Ga0P0BUkA2V3YXycy+BnzlFJl4XbavcrJWo4yx6OoNohNZ5TZDpOofV8bLSqfg+vVLqk617e1/54=
  app: viewing-party-denver
  skip_cleanup: true
  on:
    branch: main
  run: rails db:migrate
